name: "NanoNVR"
description: "The tiniest NVR."
version: "1.4.2"
slug: "nanonvr"
url: "https://github.com/mancontr/nanonvr"
image: "mancontr/nanonvr"
init: false
ingress: true
homeassistant_api: true
panel_icon: mdi:cctv
ports:
  21821/tcp: 21821
  21822/tcp: 21822
ports_description:
  21821/tcp: "FTP Control connection port"
  21822/tcp: "FTP Data connection port"
map:
  - config:rw
  - share:rw
services:
  - "mqtt:want"
arch:
  - aarch64
  - amd64
  - armv7
